baseURL = "https://github.com/danielleit241"
relativeURLs = true
canonifyURLs = true

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = "AWS Workshop"
  author = ""
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
  [[params.authors]]
    name = "Quốc Hào"
    url = "https://www.linkedin.com/in/quochaotrieu"

  [[params.authors]]
    name = "Lam Giang"
    url = "https://www.linkedin.com/in/lam-giang"

  [[params.authors]]
    name = "Bảo Minh"
    url = "https://www.linkedin.com/in/minh-tr%E1%BA%A7n-327286218"

  [[params.authors]]
    name = "Anh Duy"
    url = "https://www.linkedin.com/in/dazielvad"

  [[params.authors]]
    name = "Công Minh"
    url = "https://www.linkedin.com/in/nguy%E1%BB%85n-c%C3%B4ng-minh-796553352"
  
  [[params.authors]]
    name = "Duy Khiêm"
    url = "https://www.linkedin.com/in/the-khiem7"

  [[params.authors]]
    name = "Phương Hòa"
    url = "https://www.linkedin.com/in/danielle241"
[Languages]
[Languages.en]
title = "Workshop Documentation"
weight = 1
languageName = "English"

[Languages.vi]
title = "Tài liệu Workshop"
weight = 2
languageName = "Tiếng Việt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
